### ISSUE TITLE
lockglyph on side of the screen?

### ISSUE THREAD

**Issue by AWS12893** [Sticktron/LockGlyphX#35]
lockglyph is on the side of my screen instead of where it's supposed to be for some reason. was this made like this in an update? or is it a bug?

**Comment by Sticktron** [comment]
Is this on an iPad?

Sent from my iPhone

On Feb 25, 2017, at 6:11 PM, dairishspartan <notifications@github.com<mailto:notifications@github.com>> wrote:


lockglyph is on the side of my screen instead of where it's supposed to be for some reason. was this made like this in an update? or is it a bug?

**Comment by AWS12893** [comment]
no it's on my iphone, but it fixed itself while i wasn't using my phone
